name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: pngmn/actions-recent-changelog@main
      with:
        input: test/changelog.md
        output: test/RECENT_CHANGES.md
    - name: Output recent changes
      run: cat test/RECENT_CHANGES.md
